{function,problem5, 0, 1}.
  {label,0}.
    {func_info,{atom,euler},{atom,problem},0}.
  {label,1}.
    {move,{integer,2},{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,2}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,2}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,2}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,3}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,3}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,5}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,7}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,11}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,13}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,17}],{x,0}}.
    {gc_bif,'*',{f,0},1,[{x,0},{integer,19}],{x,0}}.
    return.
    